### PR TITLE
Add Corvus implementation

### PR DESCRIPTION
**Pull request by michaelmior**

### CODE REVIEW

**Comment by jviotti** [comment]
Looks like its not even running for some schemas?

Screenshot 2024-09-29 at 12 27 49 pm

**Comment by jviotti** [comment]
Also, I was not expecting C# to be this slow... maybe we should compile it in some "release" mode or something? cc @mwadams in case we are missing something

**Comment by mwadams** [comment]
What is missing is that Corvus.JsonSchema is an build-time code generator.

So what you are benchmarking is the entire cost of emitting the code, compiling it with Roslyn and *then* running the benchmark.

For ahead-of-time scenarios we really need two phases; the build-time bit and then the runtime bit which is actually benchmarked.

**Comment by michaelmior** [comment]
@mwadams The timing is output by the program at runtime. Compile time is not included.

**Comment by mwadams** [comment]
Hmm. I am also not expecting that to be that slow! Point me at the branch when you get a chance.

(Although other thoughts are that we validate format *by default* which may have an impact.)

**Comment by michaelmior** [comment]
The branch is the one used for this PR. It's very possible I'm doing something wrong as I've never used Corvus.JsonSchema before and I have very minimal C# experience.

https://github.com/sourcemeta-research/jsonschema-benchmark/tree/corvus

**Comment by mwadams** [comment]
So, I'm just trying out the individual schema and instances in BenchmarkDotnet on my box:


| Method   | Mean     | Error   | StdDev  |
|---------- |---------:|--------:|--------:|
| AWSCDK | 269.7 us | 0.82 us | 0.68 us | 
| BABELRC | 647.7 us | 2.46 us | 2.30 us |
| CYPRESS | 1277.0 us | 5.4 us | 4.5 us |

Initially these look to be orders of magnitude faster than those measured above, and more like I would have expected to see. So I'll investigate properly...

**Review by jviotti — APPROVED** [review]

**Comment by jviotti** [comment]
Thanks a lot @mwadams! There might something off when running it on Linux, or maybe we need to run it with optimisations enabled / release mode, or something like that? Like @michaelmior, I have never done any C# before.

**Comment by michaelmior** [comment]
@mwadams Thanks for the help! I want to be clear that I'm not trying to disparage Corvus.Json here. I'd really like to understand how to make it perform as intended for a fair comparison.

**Comment by mwadams** [comment]
Not at all! Anything like this is great because we just want to make it better, and easier to do "the right thing" out of the box.

For example, running these benchmarks means I've discovered a nasty allocation regression when using unevaluated properties/items...

Which will now go into the benchmarks suite and produce a nice little fix.

**Comment by michaelmior** [comment]
@mwadams Interesting about `format` validation by default. I personally think I like that behavior, but it seems to go contrary to the specification which states that `format` is just annotation by default, but implementations may optionally choose to have it affect validation.

**Comment by mwadams** [comment]
You can turn it off easily with a command line switch... But we originally built this *for* format validation, so when this was all internal, it meant we had fewer command line switches 😉

**Comment by jviotti** [comment]
@michaelmior It is not right now, as its optional according to the spec, but I do want to implement it!

**Comment by michaelmior** [comment]
@jviotti Okay, great. I've turned this off for Corvus.Json. We should double-check that this is disabled for other implementations.

**Comment by mwadams** [comment]
BTW - this has helped me find an issue in v4-preview where I was [deliberately, as it almost certainly an error on the schema-writer's part] throwing an exception in a property-hiding scenario

In the code-climate schema they've got subschema that look like this:
```
"argument-count": {
  "title": "Argument Count",
  "$ref": "#/definitions/enabled",
  "properties": {
    "config": {
      "$ref": "#/definitions/config",
      "properties": {
        "threshold": {
          "$ref": "#/definitions/threshold",
          "default": 4
        }
      }
    }
  }
```

But in draft4 `$ref` is sibling-hiding so those additional "properties" should be ignored.

Is this because it has come from a later draft and been "back-ported" to draft4 or is it actually an error/redundancy in this schema?

If we see this kind of thing in the wild, I'll revert to the V3 behaviour of not throwing the exception and just silently ignore the hidden keywords; it makes me think I should have some kind of logging/notification system you can opt into for more diagnostics, though,

**Comment by michaelmior** [comment]
@mwadams The schemas are currently mostly coming from [JSON Schema Store](https://www.schemastore.org/json/) so we didn't author them. I wasn't aware of the sibling hiding behavior in draft 4 you mentioned. It looks like whoever wrote the schema might not have been aware of this.

**Comment by jviotti** [comment]
@mwadams 

> If we see this kind of thing in the wild, I'll revert to the V3 behaviour of not throwing the exception and just silently ignore the hidden keywords; it makes me think I should have some kind of logging/notification system you can opt into for more diagnostics, though,

I'm silently ignoring them, and plan to elevate them as warnings on my WIP linter: https://github.com/sourcemeta/jsonschema/blob/main/docs/lint.markdown

**Comment by michaelmior** [comment]
@mwadams I made a few updates that's resolved a few of the errors. There are still some schemas were Corvus seems to generate invalid code. I'm not a .NET guy, so I'd appreciate if you get a chance to look sometime. Happy to open an issue on the Corvus repo with details if that would help.

**Comment by mwadams** [comment]
> @mwadams I made a few updates that's resolved a few of the errors. There are still some schemas were Corvus seems to generate invalid code. I'm not a .NET guy, so I'd appreciate if you get a chance to look sometime. Happy to open an issue on the Corvus repo with details if that would help.

An issue with repros would be great. I would like to get the fixes in next week.

**Comment by mwadams** [comment]
I also realised that the way the benchmarks are being run with a stopwatch and a really short run are going to be highly susceptible to transient issues.

When doing benchmark.net benchmarks, I usually configure it to run a warmup of a few thousand runs to make sure the code is all jitted optimally, then time ~1s worth of runs and divide by the number of iterations to get a single run time. Then do that ~10 times, throw away any outliers and produce the average of the remainder.

That usually gives pretty consistent results for any given hardware.

**Comment by michaelmior** [comment]
@mwadams That's fair. I would agree that how the benchmarks are being run now is suboptimal and that's something that we're hoping to improve. Your approach with benchmark.net seems pretty reasonable. I'll create an issue with some of the problematic schemas.

**Comment by michaelmior** [comment]
@mwadams I've reported a few issues. The bad news is that it seems to be several small things rather than one problem to fix. The good news is that I'm guessing each of these issues are fairly simple in themselves.

**Comment by mwadams** [comment]
Yup - it's mostly the same small thing in different guises, actually! To do with naming heuristics.

**Comment by jviotti** [comment]
> When doing benchmark.net benchmarks, I usually configure it to run a warmup of a few thousand runs to make sure the code is all jitted optimally, then time ~1s worth of runs and divide by the number of iterations to get a single run time. Then do that ~10 times, throw away any outliers and produce the average of the remainder.

Though I think taking cold runs into account is definitely powerful and realistic. On a real world scenario (i.e. an API), you will not warm up by running thousands of times.

**Comment by michaelmior** [comment]
@jviotti It depends who is doing the validating. If the validation is happening server side, I think it's reasonable that you *would* run thousands of times to warm up. Not that there necessarily is an explicit warmup, but that would be the steady state after your API has been running a little while.

**Comment by jviotti** [comment]
@michaelmior I vote for keeping track of both cold runs and warm runs. I think by doing that, we make both the benchmark and the paper a lot stronger, as we cover cases where we can assume the service has enough time to warmup, but also other common cases like CLI validation, editor integration, etc. Noting down which implementations have a huge delta due to warmup is also a very important data point.

**Pull request merged**
